# Generated by Django 2.1.3 on 2018-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_auto_20181122_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repo',
            name='repo_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repo',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
